---
- name: Respond to Gitea events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  
  rules:
    - name: Debug all other events
      condition: true
      action:
        debug:
